controller_list: 
  - name: robot_arm_controller 
    action_ns: follow_joint_trajectory 
    type: FollowJointTrajectory 
    default: true 
    joints: 
      - joint_base_waist 
      - joint_waist_arm01 
      - joint_arm01_arm02 
      - joint_arm02_arm03 
      - joint_arm03_wrist 
  - name: hand_ee_controller 
    action_ns: follow_joint_trajectory 
    type: FollowJointTrajectory 
    joints: 
      - joint_wrist_motor_gear