robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_base_waist, joint_waist_arm01, joint_arm01_arm02, joint_arm02_arm03, joint_arm03_wrist]

hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_wrist_motor_gear]

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
